[build]
  publish = "."
  command = "pip install -r pyproject.toml && streamlit run app.py --server.port 8501 --server.address 0.0.0.0"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200