[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00d4aa"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[browser]
gatherUsageStats = false

[html]
metaTags = [
    "<meta name='google-site-verification' content='gCTDmrgKgrPw_5Wh9EKQQWsDxmvSAxzzeIyps7MWC5A' />"
]
